"""add formatting structure special_requirements extracted_from_files

Revision ID: 5789bb0706f6
Revises: 97a9e4931b5c
Create Date: 2026-02-10 00:06:33.529060
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5789bb0706f6'
down_revision: Union[str, None] = '97a9e4931b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('formatting_requirements', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('structure', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('special_requirements', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('extracted_from_files', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'extracted_from_files')
    op.drop_column('orders', 'special_requirements')
    op.drop_column('orders', 'structure')
    op.drop_column('orders', 'formatting_requirements')
    # ### end Alembic commands ###
